[webhook]
url = "http://localhost:8065/hooks/xxxxxx"

[[server]]
host = "127.0.0.1"
port = 2200
user_id = "user"
user_pw = "fTRN4zGj853s+8FQ2hYKoguJMups2PUa/ZTB1AQja/s="
[[server.target]]
mount_point = "/dev/shm"
threshold = 60
[[server.target]]
mount_point = "/dev"
threshold = 80
[[server.target]]
mount_point = "/ccc"
threshold = 80

[[server]]
host = "localhost"
port = 2200
user_id = "user"
user_pw = "fTRN4zGj853s+8FQ2hYKoguJMups2PUa/ZTB1AQja/s="
[[server.target]]
mount_point = "/etc/hosts"
threshold = 80
[[server.target]]
mount_point = "/sys/firmware"
threshold = 80

[[server]]
host = "localhosta"
port = 2200
user_id = "user"
user_pw = "fTRN4zGj853s+8FQ2hYKoguJMups2PUa/ZTB1AQja/s="
[[server.target]]
mount_point = "/"
threshold = 80

[[server]]
host = "::1"
port = 2200
user_id = "user"
user_pw = "fTRN4zGj853s+8FQ2hYKoguJMups2PUa/ZTB1AQja/s="
[[server.target]]
mount_point = "/dev/shm"
threshold = 0
[[server.target]]
mount_point = "/dev"
threshold = 80
[[server.target]]
mount_point = "/ccc"
threshold = 80